# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('push_notifications', '0002_auto_20160106_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='APNSDevicesExtended',
            fields=[
                ('apnsdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.APNSDevice')),
                ('badge', models.PositiveIntegerField(default=0, help_text='Number of badges', verbose_name='Badge')),
            ],
            options={
                'abstract': False,
            },
            bases=('push_notifications.apnsdevice',),
        ),
    ]
